# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1919, 1112)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(-30, -53, 2050, 1150))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("button1.jpg"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 56, 671, 800))   #600, 20, 641, 10
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("giphy.gif"))  #"jarvis-gif-unscreen (1).gif"
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 631, 220))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("initial.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 200, 470, 360))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("new3.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1280, 155, 470, 461))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("iron man.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1320, 840, 251, 130))  #1240, 500, 601, 341
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Start1.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1600, 840, 251, 130)) 
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Quit.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 580, 440, 420))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("jarvis new.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1575, 25, 250, 120))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("g51.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1250, 25, 290, 120))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("g51.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1230, 635, 220, 180))  #1475, 650, 210, 170
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("jarvis gif.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_9")
        
        
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1450, 621, 320, 220))  #1475, 650, 210, 170
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Jarvis_Gui (1).gif"))  #jarvis icon.gif
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_9")
         
        
        
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1277, 49, 311, 131)) 

        self.textBrowser.setStyleSheet("border-radius: none;\n"                                   
"background:transparent;\n"
"color:pink;\n"
"font-size:40px;"
"font-weight:bold;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1599, 49, 315, 131))
        self.textBrowser_2.setStyleSheet("border-radius: none;\n"
"background:transparent;\n"
"color:pink;\n"
"font-size:42px;\n"
"font-weight:bold;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1355, 840, 191, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(68)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: green;\n"
"background-color: transparent;\n"
# "color: red;")
"color: transparent;")        
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1640, 840, 171, 120))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(70)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: red;\n"
"background-color: transparent;\n"
# "color: red;")
"color: transparent;") 
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
